### ISSUE TITLE
Star counter bugs out in my profile page.

### ISSUE THREAD

**Issue by NikolaPeevski** [circleteach/circleteach#15]
If I star a post, refresh the app and star it again it shows as if I starred it twice. I can continue repeating this to infinity

![image](https://user-images.githubusercontent.com/14194863/56815070-11d86e80-6806-11e9-8393-6c8697432814.png)

**Comment by mrogers8** [comment]
We've started addressing this bug- users can now star individual posts, but we will be slightly changing the data structure to account track which users have starred which posts.

**Comment by NikolaPeevski** [comment]
Amazing, thank you for addressing it :)

**Comment by flowconnor** [comment]
This has been fully fixed now. Thanks!
