### ISSUE TITLE
No password error message

### ISSUE THREAD

**Issue by sw8lde** [circleteach/circleteach#2]
Severity: low

Description: when creating a new password no error message displays if a password is not valid. I suggest just adding a message that says the minimum length and other requirements.

**Comment by parlough** [comment]
Fixed by b8cbca79e26a796bec814f373d577cee1134b0b7 - Now has error messages for all three required fields

Thanks for the report!

**Comment by WillyWaser** [comment]
Still a persistant bug :) You're checking on all 3 fields for a **valid signUp name** shouldn't it be signupPassword ? https://github.com/circleteach/circleteach/blob/master/src/app/login/login.component.html#L71

**Comment by parlough** [comment]
@WillyWaser You're correct, thanks for pointing this out! Fixed in 34be889dc90c278541d92a21576b2dfe3a528209
